var annotated_dup =
[
    [ "authenticationservice", "classauthenticationservice.html", "classauthenticationservice" ],
    [ "CommentDelegate", "class_comment_delegate.html", "class_comment_delegate" ],
    [ "dataservice", "classdataservice.html", "classdataservice" ],
    [ "EmailServerDetails", "class_email_server_details.html", "class_email_server_details" ],
    [ "EmailService", "class_email_service.html", "class_email_service" ],
    [ "LoginForm", "class_login_form.html", null ],
    [ "LoginLandingPage", "class_login_landing_page.html", null ],
    [ "MainDashboard", "class_main_dashboard.html", null ],
    [ "MainWindow", "class_main_window.html", null ],
    [ "MessageDelegate", "class_message_delegate.html", "class_message_delegate" ],
    [ "NewProjectForm", "class_new_project_form.html", null ],
    [ "NewTaskForm", "class_new_task_form.html", null ],
    [ "OtherProjectsDialog", "class_other_projects_dialog.html", null ],
    [ "Profile", "class_profile.html", null ],
    [ "ProjectChat", "class_project_chat.html", null ],
    [ "ProjectDataService", "class_project_data_service.html", "class_project_data_service" ],
    [ "ProjectMessage", "class_project_message.html", "class_project_message" ],
    [ "ProjectSettingsPage", "class_project_settings_page.html", null ],
    [ "QuickLoginPage", "class_quick_login_page.html", null ],
    [ "RegisterForm", "class_register_form.html", null ],
    [ "SearchTasksAllProjectsDialog", "class_search_tasks_all_projects_dialog.html", null ],
    [ "Task", "class_task.html", "class_task" ],
    [ "TaskComment", "class_task_comment.html", "class_task_comment" ],
    [ "TaskDataService", "class_task_data_service.html", "class_task_data_service" ],
    [ "TaskDelegate", "class_task_delegate.html", "class_task_delegate" ],
    [ "TaskDetails", "class_task_details.html", null ],
    [ "TaskSearchResultDelegate", "class_task_search_result_delegate.html", "class_task_search_result_delegate" ],
    [ "TaskStates", "class_task_states.html", "class_task_states" ],
    [ "Time", "class_time.html", null ],
    [ "user", "classuser.html", "classuser" ],
    [ "UserRoles", "class_user_roles.html", "class_user_roles" ],
    [ "Validator", "class_validator.html", null ]
];